download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/cisco-iosxr-12.0.0.tar.gz
format_version: 1.0.0
name: iosxr
namespace: cisco
server: https://galaxy.ansible.com/api/
signatures: []
version: 12.0.0
version_url: /api/v3/plugin/ansible/content/published/collections/index/cisco/iosxr/versions/12.0.0/
